name: flutter_map_supercluster
description: Very fast Marker clustering for flutter_map. Supports efficient adding/removing of Markers.
version: 5.0.1
homepage: https://github.com/rorystephenson/flutter_map_supercluster
topics:
  - flutter-map
  - cluster

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.11.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  flutter_map_marker_popup:
    git:
      url: https://github.com/Oleksii-Milkov/flutter_map_marker_popup_fork.git
  latlong2: ^0.9.0
  provider: ^6.1.1
  supercluster:
    git:
      url: https://github.com/Oleksii-Milkov/supercluster_dart_fork.git

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
